# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e67c5e667153e98c8dcee6185d56269d693f7cf164653d4d694d520cd3f001783d34dc3c387a369a755856cae7c93a3c8f2f085716161552e16e28d5fcf09da7

test:
  secret_key_base: eff7c54d270189951c0795b8954562cdf6666ba3327c4771abd9e0ccef70222877f6b8232bed591d35916d0bf38355004cdc5b512752271921589e11d2bee2ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
